apiVersion: apps/v1
kind: Deployment
metadata:
   name: docker-k8s-demo-deployment
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         app: docker-k8s-demo
   template:
      metadata:
         labels:
            app: docker-k8s-demo
      spec:
         containers:
            - name: docker-k8s-demo
              image: dockertrainingbykul/dockerdemo
              port:
                containerPort: 9090