spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/dnyaneshar/config-server/edit/main/application.yml
          clone-on-start: true
